export default {
    // common
    CARSHARE: "Car Share",
    CARSHARE_DESC: "Carpool with friends or strangers!",
    WELCOME: "Welcome to Car Share!",
    WELCOME_DESC: "To start using the application, please login or register.",
    HOME: "Home",
    PROFILE: "Profile",
    GROUPS: "Groups",
    ADMIN: "Admin",
    SUPER_ADMIN: "Super admin",
    USER: "User",
    MALE: "Male",
    UNSPECIFIED: "Not specified",
    FEMALE: "Female",
    ERROR: "Error",
    SEARCHING: "Searching",
    PRICE: "Price",
    INFORMATIONS: "Informations",
    STEPS: "Steps",
    DEFAULT: "Default",
    SENDING_RESPONSE: "Sending response",
    DELETING: "Deleting",
    CREATOR: "Creator", 
    CREATION_DATE: "Creation date",
    CANCELED: "Canceled",
    FINISHED: "Finished",

    // languages (do not translate)
    ENGLISH: "English",
    FRENCH: "Français",

    // 404 page
    WOOPS: "Woops!",
    NOT_FOUND: "The page you are looking for does not exist 🤔",
    UNKNOWN_ERROR: "A unknown error occurred",

    // validation page
    VALIDATION_TITLE: "Account validation",
    VALIDATION_LOADING: "Validating account",
    VALIDATION_SUCCESS: "Account validated successfully!\nYou can close this page.",
    VALIDATION_NO_TOKEN: "No token provided in the link,\nplease check the link you received by email.",

    // reinit password page
    REINIT_PASSWORD_TITLE: "Reset password",
    REINIT_NO_TOKEN: "No token provided in the link",
    PASSWORD_REINIT_SUCCESS: "Password reset successfully !",

    // Recovery page (forgot password)
    RECOVERY_TITLE: "You forgot your password ?",
    RECOVERY_DESC: "No problem ! We will send you an email to reset your password.",

    // actions
    LOGIN: "Login",
    REGISTER: "Register",
    LOGOUT: "Logout",
    VALIDATE: "Validate",
    CANCEL: "Cancel",
    EDIT: "Edit",
    DELETE: "Delete",
    DELETE_ALL: "Delete all",
    DELETE_ACCOUNT: "Delete account",
    ADD: "Add",
    SEARCH: "Search",
    VERIFY: "Verify",
    CHANGE: "Change",
    BACK: "Back",
    CREATE: "Create",
    DISCONNECT: "Logout",
    LOAD_MORE: "Load more",

    // register
    REGISTER_TITLE: "Register",
    REGISTER_DESC: "Please fill the fields below to register",
    FIRSTNAME: "First name",
    LASTNAME: "Last name",
    EMAIL: "Email",
    PHONE: "Phone",
    PASSWORD: "Password",
    PASSWORD_CONFIRM: "Password confirmation",
    PWD_CONFIRM: "Confirmation",
    GENDER: "Gender",
    I_HAVE_A_CAR: "I have a car",
    LEVEL: "Level",
    REQUIRED_FIELDS: "Required fields",
    INPUT_VERIFICATION: "Input verification",
    DATA_SENDING: "Sending data",
    REGISTER_SUCCESS: "Account created successfully!",
    SENDING_EMAILVERIF: "Sending email verification",
    SENDING_EMAIL_SUCCESS: "Email sent successfully!",

    // checks errors
    FIRSTNAME_SPECIFY: "Please specify the first name",
    LASTNAME_SPECIFY: "Please specify the last name",
    EMAIL_SPECIFY: "Please specify the email address",
    PHONE_SPECIFY: "Please specify the phone number",
    PASSWORD_SPECIFY: "Please specify the password",
    PASSWORD_CONFIRM_SPECIFY: "Please confirm the password",
    NAME_SPECIFY: "Please specify the name",

    FIRSTNAME_TOOLONG: "The first name is too long",
    LASTNAME_TOOLONG: "The last name is too long",
    EMAIL_TOOLONG: "The email address is too long",

    EMAIL_INVALID: "The email address is invalid",
    PHONE_INVALID: "The phone number is invalid",
    PASSWORD_UNMATCH: "The passwords do not match",

    PASSWORD_ERRLEN: "The password must be at least 10 characters long",
    PASSWORD_ERRMAJ: "The password must contain at least one uppercase letter",
    PASSWORD_ERRMIN: "The password must contain at least one lowercase letter",
    PASSWORD_ERRNBR: "The password must contain at least one number",
    PASSWORD_ERRSPE: "The password must contain at least one special character",

    // login
    LOGIN_TITLE: "Login",
    LOGIN_DESC: "Please fill the fields below to login",
    FORGOT_PASSWORD: "Forgot password?",
    LOGIN_SUCCESS: "Logged in successfully!",
    
    // main screen
    STARTING_POINT: "Departure",
    ENDING_POINT: "Arrival",
    DATE: "Date",
    HOUR: "Hour",
    CREATE_TRIP: "Create a trip",
    EDIT_TRIP: "Edit the trip",
    TRAVEL_CARD_LABEL: "Travel of the {DATE}",
    SLOTS: "Slots",
    SLOT: "Slot",
    STARTING_POINT_SPECIFY: "Please specify the starting point",
    ENDING_POINT_SPECIFY: "Please specify the ending point",
    DATE_SPECIFY: "Please specify the trip date",
    NO_TRIPS: "No trips found",
    NO_TRIPS_DESC: "No trips found for the selected informations",
    TRIP_DETAILS: "Trip details",
    PASSENGERS: "Passengers",
    NO_PASSENGERS: "There is no passenger for this trip yet",
    TRIP_DESTINATIONS: "Trip destinations",
    BOOK_TRIP: "Book the trip",
    DRIVER: "Driver",

    // profile
    MY_PROFILE: "My profile",
    MY_INFOS: "My informations",
    MY_NOTIFS: "My notifications",
    MY_EVALS: "My evaluations",
    MY_TRIPS: "My trips",
    MY_GROUPS: "My groups",
    PARAMS: "Settings",

    // informations
    CHANGING_PASSWORD: "Changing password",
    PASSWORD_CHANGED: "Password changed successfully",
    CHANGING_INFORMATIONS: "Changing informations",
    INFORMATIONS_CHANGED: "Informations changed successfully",
    DELETING_ACCOUNT: "Deleting account",

    // notifications
    NO_NOTIFS: "You don't have any notification",
    NO_NOTIFS_DESC: "You've seen it all! There is nothing more to do here at the moment.",
    LOADING_NOTIFS: "Loading notifications",
    LOADING_NOTIFS_DESC: "Please wait while we load your notifications",
    DELETE_ALL_NOTIFS: "Delete all notifications",
    DELETE_ALL_NOTIFS_CONFIRMATION: "Are you sure you want to delete all your notifications?\nThey will be deleted, even if they are not displayed on this page.\nThis action is irreversible.",
    DELETING_NOTIFS: "Deleting notifications",
    NOTIFS_DELETED: "Notifications deleted successfully",
    ACCEPT: "Accept",
    REJECT: "Reject",
    SEE_TRAVEL: "See travel",

    // groups
    NO_GROUPS: "You haven't created any group yet",
    NO_GROUPS_DESC: "Create a group to start sharing your trips with your friends",
    NO_USERS: "No users in this group yet",
    NO_USERS_DESC: "Add users to this group to start sharing your trips with them",
    CREATE_GROUP: "Create a new group",
    GROUP_CREATE_CONFIRMATION: "Please specify the group informations to create it",
    MEMBERS: "Members",
    MEMBER: "Member",
    ADD_MEMBER: "Add a member",
    ADD_MEMBER_DESC: "Search the user you want to add to this group",
    ADDING_MEMBER: "Adding member",
    MEMBER_ADDED: "Member added successfully",
    DELETE_GROUP: "Delete group",
    DELETING_GROUP: "Deleting group",
    GROUP_DELETED: "Group deleted successfully",
    GROUP_DELETE_CONFIRMATION: "Are you sure you want to delete this group?\nThis action is irreversible.",
    GROUP_NAME: "Group name",
    CREATING_GROUP: "Creating group",
    GROUP_CREATED: "Group created successfully",
    LOADING_GROUPS: "Loading groups",
    LOADING_GROUPS_DESC: "Please wait while we load your groups",
    SELECT_GROUP: "Select a group",
    SELECT_GROUP_DESC: "Please select a group of users to share your trip with",
    GROUP_SELECTED: "Group selected",
    SEARCH_GROUP: "Search group",

    // parameters
    NOTIF_PARAMS: "Notification settings",
    EMAIL_NOTIFICATIONS: "Notify by email",
    THEME: "Theme",
    DARKMODE: "Dark",
    LIGHTMODE: "Light",
    DISPLAY_PARAMS: "Display settings",
    LANGUAGE: "Language",
    UPDATING_PARAMS: "Updating parameters",
    ERROR_UPDATING_PARAMS: "An error occurred while updating parameters.",
    PARAMS_UPDATED: "Parameters updated successfully",
    OTHER_PARAMS: "Other settings",
    TIMEZONE: "Timezone",

    // trip
    FUTURE_TRIPS: "Future trips",
    PAST_TRIPS: "Past trips",
    CANCEL_TRIP: "Cancel trip",
    LOADING_TRIP: "Loading trip",
    LOADING_TRIP_DESC: "Please wait while we load the trip informations",
    LOADING_TRIPS: "Loading trips",
    LOADING_TRIPS_DESC: "Loading all your trips",
    MARK_AS_FINISHED: "Mark as finished",
    CANCELLING_TRIP: "Cancelling trip",
    TRIP_CANCELLED: "Trip cancelled successfully",
    MARKING_TRIP_AS_FINISHED: "Finishing trip",
    TRIP_MARKED_AS_FINISHED: "Trip finished successfully",


    // booking
    BOOKING_DOESNT_EXIST_ANYMORE: "This booking doesn't exist anymore.",

    // informations
    ADDRESS_NOT_VERIFIED: "Address not verified",
    ADDRESS_VERIFIED: "Address verified",
    ADDRESS_VERIFICATION: "A verification email has been sent to you",
    ADDRESS_ERROR: "An error occured, try again later",
    ADDRESS_ERROR_SPAM: "Email already sent, please wait 10 minutes",
    OLD_PASSWORD: "Old password",
    NEW_PASSWORD: "New password",
    ACCOUNT_DELETE_CONFIRMATION: "Are you sure you want to delete your account?\nThis action is irreversible.",

    // administration
    ADMINISTRATION: "Administration",
    USERS: "Users",
    TRIPS: "Trips",
    
    // users
    SEARCH_USER: "Search user",
    ACCOUNT_DELETE_VERIFY: "Are you sure you want to delete this account?\nThis action is irreversible.",
    GROUP_DELETE_VERIFY: "Are you sure you want to delete this group?\nThis action is irreversible.",
    ACCOUNT_EMAIL: "Account Email",
    EMAIL_VERIFICATION: "Email verification",
    EMAIL_UNMATCHING: "Emails do not match",
    ACCOUNT_DELETION: "Account deletion",
    ACCOUNT_DELETED: "Account deleted",

    // trip creation
    TRIP_TYPE: "Trip type",
    TRIP_PUBLIC: "Public",
    TRIP_PRIVATE: "Private",
    TRIP_SLOTS: "Number of slots",
    TRIP_START: "Start",
    TRIP_END: "End",
    TRIP_INFO: "Additional informations",
    SAME_DAY: "Same day",
    CONFIRM_TRIP: "Confirm trip",
    CONFIRM_TRIP_DESC: "Please verify the informations below before confirming the trip",
    EDIT_TRIP_DESC: "Please verify the informations below before editing the trip",
    CONFIRM_TRIP_CONTENT: "You are about to create a trip from {0} to {1} starting the {2} at {3} and arriving the {4} at {5}.\nThe trip will be {6} and will have {7} slots available.",
    CONFIRM_TRIP_CONTENT_1: "You are about to create a trip from {0} to {1} starting the {2} at {3} and arriving the {4} at {5}.\nThe trip will be {6} and will have {7} slot available.",
    CONFIRM_TRIP_PUBLIC: "This trip will be public and everyone will be able to see it",
    CONFIRM_TRIP_PRIVATE: "This trip will be private and only the users of the group {0} will be able to see it",
    CONFIRM_TRIP_INFOS: "Additional informations: {0}",
    CONFIRM_TRIP_NO_INFOS: "No additional informations have been specified",
    CONFIRM_TRIP_NO_STEPS: "This trip will have no steps",
    CONFIRM_TRIP_N_STEPS: "This trip will have {0} steps",
    CONFIRM_TRIP_1_STEP: "This trip will have {0} step",
    CONFIRM_TRIP_STEP: "Step {0}: You will arrive at {1} on {2} at {3}",
    CREATING_TRIP: "Creating trip",
    TRIP_CREATED: "Trip created successfully",
    EDITING_TRIP: "Editing trip",
    TRIP_EDITED: "Trip edited successfully",
    DESTINATION_SPECIFY: "Please specify all the trip destinations",
    DATETIME_SPECIFY: "Please specify all the trip dates and times",
    SLOTS_SPECIFY: "Please specify the number of slots for the trip",
    GROUP_SPECIFY: "Please specify the group of users to share the trip with",
}