export default {
    // common
    CARSHARE: "Car share",
    CARSHARE_DESC: "Covoiturez entre amis ou inconnus !",
    WELCOME: "Bienvenue sur Car Share !",
    WELCOME_DESC: "Pour commencer à utiliser l'application, veuillez vous connecter ou vous inscrire.",
    HOME: "Accueil",
    PROFILE: "Profil",
    GROUPS: "Groupes",
    ADMIN: "Admin",
    SUPER_ADMIN: "Super admin",
    USER: "Utilisateur",
    MALE: "Homme",
    UNSPECIFIED: "Non spécifié",
    FEMALE: "Femme",
    ERROR: "Erreur",
    SEARCHING: "Recherche",
    PRICE: "Prix",
    INFORMATIONS: "Informations",
    STEPS: "Étapes",
    DEFAULT: "Par défaut",

    // languages
    ENGLISH: "Anglais",
    FRENCH: "Français",

    // 404 page
    WOOPS: "Woops !",
    NOT_FOUND: "La page que vous cherchez n'existe pas 🤔",
    UNKNOWN_ERROR: "Une erreur inconnue est survenue",

    // validation page
    VALIDATION_TITLE: "Validation du compte",
    VALIDATION_LOADING: "Validation du compte",
    VALIDATION_SUCCESS: "Compte validé avec succès !\nVous pouvez fermer cette page.",
    VALIDATION_NO_TOKEN: "Aucun token n'a été fourni dans le lien,\nveuillez vérifier le lien que vous avez reçu par email.",

    // actions
    LOGIN: "Se connecter",
    REGISTER: "S'inscrire",
    LOGOUT: "Se déconnecter",
    VALIDATE: "Valider",
    CANCEL: "Annuler",
    EDIT: "Modifier",
    DELETE: "Supprimer",
    DELETE_ALL: "Tout supprimer",
    DELETE_ACCOUNT: "Supprimer le compte",
    DELETE_GROUP :"Supprimer le groupe " , 
    ADD: "Ajouter",
    SEARCH: "Rechercher",
    VERIFY: "Vérifier",
    CHANGE: "Changer",
    BACK: "Retour",
    CREATE: "Créer",
    DISCONNECT: "Se déconnecter",
    LOAD_MORE: "Charger plus",

    // register
    REGISTER_TITLE: "Inscription",
    REGISTER_DESC: "Veuillez remplir les champs ci-dessous pour vous inscrire",
    FIRSTNAME: "Prénom",
    LASTNAME: "Nom",
    EMAIL: "Email",
    PHONE: "Téléphone",
    PASSWORD: "Mot de passe",
    PASSWORD_CONFIRM: "Confirmation du mot de passe",
    PWD_CONFIRM: "Confirmation",
    GENDER: "Genre",
    I_HAVE_A_CAR: "J'ai une voiture",
    LEVEL: "Niveau",
    REQUIRED_FIELDS: "Champs obligatoires",
    INPUT_VERIFICATION: "Vérification des entrées",
    DATA_SENDING: "Envoi des données",
    REGISTER_SUCCESS: "Compte créé avec succès",
    SENDING_EMAILVERIF: "Envoi de l'email de vérification",
    SENDING_EMAIL_SUCCESS: "Email envoyé avec succès",

    // checks errors
    FIRSTNAME_SPECIFY: "Veuillez renseignez votre nom",
    LASTNAME_SPECIFY: "Veuillez renseignez votre prénom",
    EMAIL_SPECIFY: "Veuillez renseignez votre adresse mail",
    PHONE_SPECIFY: "Veuillez renseignez votre numéro de téléphone",
    PASSWORD_SPECIFY: "Veuillez renseignez votre mot de passe",
    PASSWORD_CONFIRM_SPECIFY: "Veuillez confirmer votre mot de passe",
    NAME_SPECIFY: "Veuillez renseignez le nom",
    GROUPNAME_SPECIFY: "Veuillez renseignez le nom du groupe",
    CREATOR_SPECIFY: "Veuillez renseignez le nom du créatur",

    FIRSTNAME_TOOLONG: "Le nom est trop long",
    LASTNAME_TOOLONG: "Le prénom est trop long",
    EMAIL_TOOLONG: "L'adresse mail est trop longue",

    EMAIL_INVALID: "L'adresse mail est invalide",
    PHONE_INVALID: "Le numéro de téléphone est invalide",
    PASSWORD_UNMATCH: "Les mots de passe ne correspondent pas",

    PASSWORD_ERRLEN: "Le mot de passe doit faire au moins 10 caractères",
    PASSWORD_ERRMAJ: "Le mot de passe doit contenir au moins une majuscule",
    PASSWORD_ERRMIN: "Le mot de passe doit contenir au moins une minuscule",
    PASSWORD_ERRNBR: "Le mot de passe doit contenir au moins un chiffre",
    PASSWORD_ERRSPE: "Le mot de passe doit contenir au moins un caractère spécial",

    // login
    LOGIN_TITLE: "Connexion",
    LOGIN_DESC: "Veuillez remplir les champs ci-dessous pour vous connecter",
    FORGOT_PASSWORD: "Mot de passe oublié",
    LOGIN_SUCCESS: "Connecté avec succès",

    // main screen
    STARTING_POINT: "Départ",
    ENDING_POINT: "Arrivée",
    DATE: "Date",
    HOUR: "Heure",
    CREATE_TRIP: "Créer un trajet",
    TRAVEL_CARD_LABEL: "Trajet du {DATE}",
    SLOTS: "Places",
    SLOT: "Place",
    STARTING_POINT_SPECIFY: "Veuillez renseignez le point de départ",
    ENDING_POINT_SPECIFY: "Veuillez renseignez le point d'arrivée",
    DATE_SPECIFY: "Veuillez renseignez la date",
    NO_TRIPS: "Aucun trajet trouvé",
    NO_TRIPS_DESC: "Il n'y a aucun trajet trouvé pour les informations renseignées",

    // profile
    MY_PROFILE: "Mon profil",
    MY_INFOS: "Mes informations",
    MY_NOTIFS: "Mes notifications",
    MY_EVALS: "Mes notes",
    MY_TRIPS: "Mes trajets",
    MY_GROUPS: "Mes groupes",
    PARAMS: "Paramètres",

    // informations
    CHANGING_PASSWORD: "Changement du mot de passe",
    PASSWORD_CHANGED: "Mot de passe changé avec succès",
    CHANGING_INFORMATIONS: "Changement des informations",
    INFORMATIONS_CHANGED: "Informations changées avec succès",
    DELETING_ACCOUNT: "Suppression du compte",

    // notifications
    NO_NOTIFS: "Vous n'avez aucune notification",
    NO_NOTIFS_DESC: "Vous avez tout vu ! Il n'y a plus rien à faire ici pour le moment.",
    LOADING_NOTIFS: "Chargement des notifications",
    LOADING_NOTIFS_DESC: "Veuillez patienter pendant que nous récupérons vos notifications",
    DELETE_ALL_NOTIFS: "Supprimer toutes les notifications",
    DELETE_ALL_NOTIFS_CONFIRMATION: "Êtes-vous sûr de vouloir supprimer toutes vos notifications ?\nElles seront supprimées, même si elles ne sont pas affichées sur cette page.\nCette action est irréversible.",
    DELETING_NOTIFS: "Suppression des notifications",
    NOTIFS_DELETED: "Notifications supprimées avec succès",

    // groups
    NO_GROUPS: "Vous n'avez encore aucun groupe",
    NO_GROUPS_DESC: "Créez un groupe pour pouvoir partager vos trajets avec vos amis",
    NO_USERS: "Il n'y encore aucun utilisateur",
    NO_USERS_DESC: "Ajoutez des utilisateurs à votre groupe pour pouvoir partager vos trajets avec eux",
    CREATE_GROUP: "Créer un nouveau groupe",
    GROUP_CREATE_CONFIRMATION: "Veuillez renseigner les informations du groupe pour le créer",
    MEMBERS: "Membres",
    MEMBER: "Membre",
    DELETE_GROUP: "Supprimer le groupe",
    GROUP_DELETE_CONFIRMATION: "Êtes-vous sûr de vouloir supprimer ce groupe ?\nCette action est irréversible.",
    GROUP_NAME: "Nom du groupe",
    CREATING_GROUP: "Création du groupe",
    GROUP_CREATED: "Groupe créé avec succès",
    LOADING_GROUPS: "Chargement des groupes",
    LOADING_GROUPS_DESC: "Veuillez patienter pendant que nous chargeons vos groupes",
    SELECT_GROUP: "Sélectionnez un groupe",
    SELECT_GROUP_DESC: "Veuillez sélectionner un groupe d'utilisateurs pour pouvoir partager vos trajets avec eux",
    GROUP_SELECTED: "Groupe sélectionné",
    SEARCH_GROUP: "Rechercher un groupe",
    GROUP_NAME: "Nom de groupe",
    GROUP_CREATOR :"Createur",

    //parametres
    NOTIF_PARAMS: "Paramètres de notifications",
    EMAIL_NOTIFICATIONS: "Notifier par email",
    THEME: "Thème",
    DARKMODE: "Sombre",
    LIGHTMODE: "Clair",
    DISPLAY_PARAMS: "Paramètres d'affichage",
    LANGUAGE: "Langue",
    UPDATING_PARAMS: "Mise à jour des paramètres",
    PARAMS_UPDATED: "Paramètres mis à jour avec succès",

    // informations
    ADDRESS_NOT_VERIFIED: "Adresse non vérifiée",
    ADDRESS_VERIFIED: "Adresse vérifiée",
    ADDRESS_VERIFICATION: "Un mail de vérification vous a été envoyé",
    ADDRESS_ERROR: "Une erreur s'est produite, réessayez plus tard",
    ADDRESS_ERROR_SPAM: "Email déjà envoyé, veuillez attendre 10 minutes",
    OLD_PASSWORD: "Ancien mot de passe",
    NEW_PASSWORD: "Nouveau mot de passe",
    ACCOUNT_DELETE_CONFIRMATION: "Êtes-vous sûr de vouloir supprimer votre compte ?\nCette action est irréversible.",

    // administration
    ADMINISTRATION: "Administration",
    USERS: "Utilisateurs",
    TRIPS: "Trajets",
    
    // users
    SEARCH_USER: "Rechercher un utilisateur",
    ACCOUNT_DELETE_VERIFY: "Êtes-vous sûr de vouloir supprimer ce compte ?\nCette action est irréversible.",
    GROUP_DELETE_VERIFY: "Êtes-vous sûr de vouloir supprimer ce groupe ?\nCette action est irréversible.",
    ACCOUNT_EMAIL: "Email du compte",
    EMAIL_VERIFICATION: "Vérification de l'Email",
    EMAIL_UNMATCHING: "L'Email ne correspond pas",
    ACCOUNT_DELETION: "Suppression du compte",
    ACCOUNT_DELETED: "Compte supprimé",

    // trip creation
    TRIP_TYPE: "Type de trajet",
    TRIP_PUBLIC: "Public",
    TRIP_PRIVATE: "Privé",
    TRIP_SLOTS: "Nombre de places",
    TRIP_START: "Départ",
    TRIP_END: "Arrivée",
    TRIP_STEP: "Étape",
    TRIP_INFO: "Informations supplémentaires",
    SAME_DAY: "Même jour",
    CONFIRM_TRIP: "Confirmer le trajet",
    CONFIRM_TRIP_DESC: "Veuillez vérifier les informations du trajet avant de le créer",
    CONFIRM_TRIP_CONTENT: "Vous allez faire un trajet de {0} à {1}.\nEn partant le {2} à {3} et arrivant le {4} à {5}.\nLe trajet sera au prix de {6}€ par personne et il y aura {7} places disponibles.",
    CONFIRM_TRIP_PUBLIC: "Ce trajet sera public et tout le monde pourra le voir",
    CONFIRM_TRIP_PRIVATE: "Ce trajet sera privé et seuls les membres du groupe {0} pourront le voir",
    CONFIRM_TRIP_INFOS: "Informations supplémentaires : {0}",
    CONFIRM_TRIP_NO_INFOS: "Aucune information supplémentaire n'a été renseignée",
    CONFIRM_TRIP_NO_STEPS: "Ce trajet n'aura aucune étape",
    CONFIRM_TRIP_N_STEPS: "Ce trajet contiendra {0} étapes :",
    CONFIRM_TRIP_1_STEP: "Ce trajet contiendra {0} étape :",
    CONFIRM_TRIP_STEP: "Étape {0} : Vous arriverez à {1} le {2} à {3}",
    CREATING_TRIP: "Création du trajet",
    TRIP_CREATED: "Trajet créé avec succès",
    DESTINATION_SPECIFY: "Veuillez spécifier toutes les destinations du trajet",
    DATETIME_SPECIFY: "Veuillez spécifier toutes les dates et heures du trajet",
    SLOTS_SPECIFY: "Veuillez spécifier le nombre de places disponibles pour le trajet",
    GROUP_SPECIFY: "Veuillez spécifier un groupe pour le trajet",
}