openapi: 3.0.3
info:
  title: Car Share API
  description: This is the API for the Car Share project.
  version: 0.0.1
  contact:
    name: Car Share
    email: 'contoux1u@etu.univ-lorraine.fr'
  license:
    name: GNU General Public License v3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
servers:
  - url: 'https://carshare.api.antoinectx.fr'
paths:
  /users/signup:
    post:
      summary: Create a new user
      description: Create a new user
      responses:
        '200':
          description: OK
          
  
