openapi: 3.0.3
info:
  title: Car Share API
  description: This is the API for the Car Share project.
  version: 0.0.1
  contact:
    name: Car Share
    email: 'contoux1u@etu.univ-lorraine.fr'
  license:
    name: GNU General Public License v3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
servers:
  - url: 'https://carshare.api.antoinectx.fr'
paths:
  /users/signup:
    post:
      summary: Sign up
      description: Create a new user
      tags:
        - Users
      parameters:
        - $ref: '#/components/parameters/Accept-Language'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  example: Password123$
                firstName:
                  type: string
                  example: John
                lastName:
                  type: string
                  example: Doe
                phone:
                  type: string
                  example: "+330612345678"
                gender:
                  type: integer
                  required: false
                  default: -1
                  enum:
                    - -1
                    - 0
                    - 1
                hasCar:
                  type: boolean
                  required: false
                  default: false

      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password is required

        '500':
          $ref: '#/components/responses/InternalError'


  /admin/users:
    get:
      summary: Get all users
      description: Get all users
      tags:
          - Admin
      parameters:
          - $ref: '#/components/parameters/Accept-Language'
      responses:
        '200':
          description: A list of all users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfUsers'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  parameters:
    Accept-Language:
      name: Accept-Language
      in: header
      description: The language to use in the response message (if any)
      required: false
      schema:
        type: string
        default: en
        enum:
          - en
          - fr
  responses:
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: An internal error has occurred, please try again later or contact an administrator
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: john@example.com
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        phone:
          type: string
          example: "+330612345678"
        avatar:
          type: string
          nullable: true
          default: null
        gender:
          type: integer
          default: -1
        hasCar:
          type: boolean
          default: false
        mailNotif:
          type: boolean
          default: false
        level:
          type: integer
          default: 0
        createdAt:
          type: string
          format: date-time
    ArrayOfUsers:
      type: array
      items:
        $ref: '#/components/schemas/User'
      example:
        - id: 1
          email: bob@example.com
          firstName: Bob
          lastName: LeBricoleur
          phone: "0321456789"
          avatar: null
          gender: -1
          hasCar: true
          mailNotif: true
          level: 3
          createdAt: 2023-01-26T15:26:31.144Z
        - id: 2
          email: laia@cat.world
          firstName: Laia
          lastName: Kitten
          phone: "+330612345678"
          avatar: null
          gender: 1
          hasCar: false
          mailNotif: true
          level: 1
          createdAt: 2023-02-18T13:19:23.636Z
