openapi: 3.0.3
info:
  title: Car Share API
  description: This is the API for the Car Share project.
  version: 0.0.1
  contact:
    name: Car Share
    email: 'contoux1u@etu.univ-lorraine.fr'
  license:
    name: GNU General Public License v3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
servers:
  - url: 'https://carshare.api.antoinectx.fr'
paths:
  /users/signup:
    post:
      summary: Create a new user
      description: Create a new user
      responses:
        '200':
          description: OK
  /admin/users:
    get:
      summary: Get all users
      description: Get all users
      responses:
        '200':
          description: A list of all users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfUsers'
        '500':
          description: An error occurred when trying to connect to the database
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        password:
          type: string
          format: password
        firstName:
          type: string
          nullable: true
          default: null
        lastName:
          type: string
          nullable: true
          default: null
        tel:
          type: string
          nullable: true
          default: null
        birthDate:
          type: string
          format: date
          nullable: true
          default: null
        avatar:
          type: string
          nullable: true
          default: null
        gender:
          type: integer
          default: -1
        hasCar:
          type: boolean
          default: false
        mailNotif:
          type: boolean
          default: false
        level:
          type: integer
          default: 0
        createdAt:
          type: string
          format: date-time
    ArrayOfUsers:
      type: array
      items:
        $ref: '#/components/schemas/User'
      example:
        - id: 1
          email: bob@example.com
          password: abcdef123456
          firstName: Bob
          lastName: LeBricoleur
          tel: null
          birthDate: null
          avatar: null
          gender: -1
          hasCar: true
          mailNotif: true
          level: 3
          createdAt: 2023-01-26T15:26:31.144Z
        - id: 2
          email: laia@cat.world
          password: CatzAreBeautiful
          firstName: Laia
          lastName: Kitten
          tel: 06 12 34 56 78
          birthDate: 2023-01-17
          avatar: null
          gender: 1
          hasCar: false
          mailNotif: true
          level: 1
          createdAt: 2023-02-18T13:19:23.636Z
